[package]
name = "raytrace"
version = "0.1.0"
authors = ["James <dong.james.sept14@gmail.com>"]

[dependencies]
nalgebra = "^0.4.0"
image = "^0.6.1"
rand = "^0.3.12"

[features]
nightly = []

[lib]
name = "libraytrace"
path = "src/lib.rs"

[[bin]]
name = "raytrace"
path = "src/main.rs"
doc = false
